# Generated by Django 2.0.4 on 2018-05-13 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 5, 13, 6, 44, 41, 407072, tzinfo=utc))),
                ('text', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='BlogAPI.Tag'),
        ),
    ]
