# Generated by Django 2.0.4 on 2018-05-13 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 6, 49, 36, 134184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
