# Generated by Django 2.0.4 on 2018-05-13 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0004_auto_20180513_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 11, 49, 53, 636418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 11, 49, 53, 636454, tzinfo=utc)),
        ),
    ]
