# Generated by Django 2.0.4 on 2018-05-13 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPI', '0006_auto_20180513_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('view_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posty'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tagi'},
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 12, 13, 5, 468124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 13, 12, 13, 5, 468174, tzinfo=utc)),
        ),
    ]
